### ISSUE TITLE
reasoning behind rstudioapi::isAvailable

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#101]
@Clare2D 
when running the webtool, the code checks:
`if (rstudioapi::isAvailable()) {`
in order to set the working directory. In our cleanup und fixing session, @maurolepore and I were wondering if we can just exchagne that for `interactive()`

So the question is:
Was this introduced to check if the script is being run interactively in RStudio instead of via command line? Or was there another reason that we are not seeing and that would warrant keeping the rstudioapi:: version?

**Comment by Clare2D** [comment]
Exactly. This can be changed to a neater option if preferred!

**Comment by jacobvjk** [comment]
great, will do
