### ISSUE TITLE
master or current_web_functionality

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#120]
After commit acdedabadccdcdeb05cc2e0384f9c78e77a5abd6, `current_web_functionality` is still set as the default branch of the repo, and based on the name of that commit ("Merge branch 'master' into current_web_functionality") that seems like it should be the case. Or not? Should we be primarily using "master" now, or "current_web_functionality"?

**Comment by cjyetman** [comment]
Presumably we should continue using the "current_web_functionality" branch since that is the one that still has the `docker.sh` file in it? Sorry, I'm pretty confused at the moment.

**Comment by maurolepore** [comment]
Correct. As of right now, the default branch is still `current_web_functionality` but it will be `master` when we merge #136. I'll close this issue from the merge commit.
