### ISSUE TITLE
shell variables in docker.sh should be quoted

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#122]
It is my understanding that when using shell variables that contain strings (as in [docker.sh](https://github.com/2DegreesInvesting/PACTA_analysis/blob/current_web_functionality/docker.sh)), one should always quote them to avoid problems, e.g. a path with spaces in it.

for example...
`data=$(dirname $(pwd))/pacta-data`
should be...
`data=$(dirname "$(pwd)")/pacta-data`

and...
```
docker run --rm -ti \
  --mount type=bind,source=$analysis,target=/bound
```
should be...
```
docker run --rm -ti \
  --mount type=bind,source="$analysis",target=/bound
```

**Comment by maurolepore** [comment]
Solved
