### ISSUE TITLE
fund_data.fst does not exist (in pacta-data)

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#123]
this line in `web_tool_script_1.R`
https://github.com/2DegreesInvesting/PACTA_analysis/blob/acdedabadccdcdeb05cc2e0384f9c78e77a5abd6/web_tool_script_1.R#L99

fails with...
`Error: '/pacta-data/2019Q4/cleaned_files/fund_data.fst' does not exist.`

**Comment by cjyetman** [comment]
unless we change `WebParameters_docker.yml` so that `new_data: TRUE`, then `web_tool_script_1.R` will fail because it expects an archived version of `fund_data.fst` to be there

**Comment by maurolepore** [comment]
Considering the file '/pacta-data/2019Q4/cleaned_files/fund_data.fst' is optional, and that it has been the cause of bugs, I suggest we remove the option. That seems the easiest, fastest, and safest way to crush the bug -- giving us time to focus on non-optional code and making the code base simpler and more maintainable.

**Comment by cjyetman** [comment]
To be clear, I don't think it's about "removing" an option... it's a choice of whether we set `new_data: TRUE` or `new_data: FALSE` (and there are more than one YML that can be used to make that choice depending on how/where the scripts are being run).

If the parameter is set to `new_data: TRUE`, then the script will create the data files on the fly (in which case, we need to sort out these `.rda` inconsistencies so that it can successfully complete (see #124)).

If the parameter is set to `new_data: FALSE`, then the script will expect to find archived versions of the datasets in `../pacta-data`, which could be done one way or another, but is undesirable specifically for the `pacta-data/2019Q4/cleaned_files/fund_data.fst` file because it is so large.

**Comment by jacobvjk** [comment]
@cjyetman 
Regarding the funds data: I agreed with @Clare2D to skip reading in the `fund_data.fst` file if it does not exist in the specified directory, given `new_data ==FALSE`. Regarding the latter, we will discuss an alternative workflow for updating such data tomorrow, but for the time being we would leave that switch in the code (with the parameters set to FALSE). FALSE should clearly be the default, but TRUE is not entirely irrelevant.

Regarding the further handling of the fund data, if it cannot be read in, there should be no problem. it is only used by the function `process_raw_portfolio()` in web_tool_script_1.R. If you take a look here https://github.com/2DegreesInvesting/PACTA_analysis/blob/acdedabadccdcdeb05cc2e0384f9c78e77a5abd6/0_portfolio_input_check_functions.R#L1044 there is functionality in there that handles the fund_data not being available.

**Comment by maurolepore** [comment]
CJ, at the end of our last meeting we discussed where to push commits -- like the one that would solve this issue. Then, we agreed to push to current_web_functionality, but that branch is right now on a broken state -- the integration test fails on GitHub Actions currently fails. Notice that https://github.com/2DegreesInvesting/PACTA_analysis/pull/127 reverts the repo to the latest passing state. So you may want to branch off https://github.com/2DegreesInvesting/PACTA_analysis/pull/127 and test your work locally with:

```r
devtools::load_all()
test_integration()
```

Once https://github.com/2DegreesInvesting/PACTA_analysis/pull/127 is merged into `current_web_functionality` you could rebase your commits on top and submit a PR.

**Comment by cjyetman** [comment]
@maurolepore ok, but I will probably need some guidance because I'm not sure how to do any of that

**Comment by maurolepore** [comment]
Fortunately #127  is now merged and you should be able to rebase you commits on top of it. Ping me on Slack if you want to connect on a call and discuss.

**Comment by cjyetman** [comment]
this is fixed by #129 because the `read_file` function now gracefully fails if the file does not exist... closing
