### ISSUE TITLE
Incorporate Executive Summary into web_script_4

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#126]
Another that needs to be printed, is a 2 page pdf executive summary for each portfolio. 

A new repo has been created here: https://github.com/2DegreesInvesting/P2020_executive_summary

The document is going to be developed further by Andy. It should be printed within web_script_3 or _4 by a simple function. 

This is where new content for the exec summary shall be placed. To be done still is to create the command to generate this, add real content to this. 

We should discuss work flow and where this should live!

**Comment by Clare2D** [comment]
I've just changed the name of the repo to create_executive_summary and will create a function that wraps around it that can be called from web_script_3 (at least to begin with)

**Comment by maurolepore** [comment]
Seems straight forward:

``` r
# If you have an .Rmd file with "output: pdf_document" ...

input_file_rmd <- tempfile(fileext = ".Rmd")
text <- c(
  "---",
  "output: pdf_document",
  "---",
  "",
  "Some prose and some code."
)
writeLines(text, input_file_rmd)



# .. you can render it from anywhere, e.g. from a script in PACTA_analysis

(output_file_pdf <- tempfile(fileext = ".pdf"))
#> [1] "/tmp/RtmpYcnWnq/file6d1673ee5786.pdf"

rmarkdown::render(input_file_rmd, output_file = output_file_pdf)
#> processing file: file6d1665482e49.Rmd
#> output file: file6d1665482e49.knit.md
#> /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS file6d1665482e49.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/RtmpYcnWnq/file6d1673ee5786.tex --lua-filter /home/mauro/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/mauro/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in'
#> 
#> Output created: /tmp/RtmpYcnWnq/file6d1673ee5786.pdf
```

<sup>Created on 2020-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

--

If the executive summary and the report are both closely related, I think they belong to the same git repository. That way
we can track the evolution (versions) of both files.

**Comment by Clare2D** [comment]
done
