### ISSUE TITLE
Outsource new_data==TRUE logic from web_tool_script_1.R

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#130]
https://github.com/2DegreesInvesting/PACTA_analysis/blob/a25b552c66d69ea169c9f14791e45df8a2c1cdf1/web_tool_script_1.R#L65

Regarding this switch, @Clare2D  and I were thinking about outsourcing this to another script in this repo that is not called from the webtool scripts so it does not interfere with them running. this new script would check that the data for the webtool is in the right format and it would be possible to trigger an update of the pacta-data. It would only be called internally. Any opinions on this @cjyetman @maurolepore

**Comment by cjyetman** [comment]
related to #123

**Comment by maurolepore** [comment]
I don't understand enough to suggest anything here. But I'm happy to review a draft PR or draft it myself if we pair program.

**Comment by jacobvjk** [comment]
That's fine, I would want to get some of the essential remaining issues done first, but hopefully get back to this asap then

**Comment by cjyetman** [comment]
I don't think this is an issue anymore... `new_data` seems to always be `FALSE` now. Frankly, I have no idea why or how. Maybe something changed when the default branches were getting moved around?

I thought that what was in [parameter_files/WebParameters_docker.yml](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/parameter_files/WebParameters_docker.yml) and in [parameter_files/WebParameters_2dii.yml](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/parameter_files/WebParameters_2dii.yml) were different, but now they both have `new_data: FALSE`, and git claims those lines haven't been changed for months.

🤷

**Comment by cjyetman** [comment]
this has been superseded by #235
