### ISSUE TITLE
Do we support dplyr 0.8.5?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#138]
In R, we generally assume that users have up-to-date packages. And I'm generally okay with this assumption, except maybe for dplyr. dplyr 1 is still relatively recent, and introduced a number of braking changes. 

I recommend we test if this code base can support dplyr 0.8.5, and if we do depend on dplyr 1, state it explicitely -- maybe with something like

```r
if (packageVersion("dplyr") < 1) stop("dplyr must be 1.0.0 or greater")
```

**Comment by cjyetman** [comment]
Has `tidyverse` given any guidance / made any suggestions about this?

I fear this may not be completely possible... for instance, there has already been discussion about adding the `.groups = "drop"` option to `dplyr::summarise` calls to avoid flooding the console with warnings... not sure if that is compatible with  dplyr v0.8.5

**Comment by cjyetman** [comment]
since we've already moved forward using the `.groups = "drop_last"` throughout the code in this repo, I think maybe this is a moot point already? though, I guess that the `.groups = "drop_last"` argument should not cause `dplyr`v0.8.5 to error, but it will probably ignore the unwon argument and possibly give a warning?

**Comment by cjyetman** [comment]
I vote for supporting dplyr v1.0.0+

It's been a long treacherous road, with multiple wrong turns and misdirections, but dplyr finally made it to v1, and if they stick to their stated intent, v1.0.0+ will have a stable, backward compatible api. That can't be said for < v1.0.0, where it gets much more murky. v0.8.5 is only one release version behind v1.0.0, and it's now 9 months old, so I don't see there being much value in forcing ourselves to support it.

**Comment by maurolepore** [comment]
:+1:

**Comment by maurolepore** [comment]
Just for the record, as we have been discussing general refactoring strategies with @cjyetman and @MonikaFu.

Here is one PR that future-proofs a package for dplyr 1 while allowing dplyr 0.8.5. The code behaves as it should depending on which version is installed; and the code does not need to change when we eventually support dplyr 1.

**Comment by cjyetman** [comment]
in the PR 2DegreesInvesting/r2dii.match#317...

that's defending against one specific change between tidyselect <1 and tidyselect >=1, but not all possible conflicting changes, right? or am I missing something

I like the concept of it, but one must already know/have identified all of the conflicting changes relevant to a given project, and provide alternative solutions for each one, right?

**Comment by maurolepore** [comment]
> that's defending against one specific change between tidyselect <1 and tidyselect >=1, but not all possible conflicting changes, right?

Right -- regarding the release of tidyselect 1, that PR addresses one specific issue so we can continue to support tidyselect <1 (and dplyr <1) and use one feature of tidyselect > 1 if it is available.

However, I shared this here not to show the specific solution that I coded, but show a pattern that can sometimes help make code more maintenable.

**Comment by cjyetman** [comment]
cool, thanks. yeah just wanted to clarify if/that to achieve the same thing here (or elsewhere) each possible difference needs to be identified and an alternative created

**Comment by maurolepore** [comment]
Just to complete my comment I'll add one reference:

https://principles.tidyverse.org/changes-multivers.html
