### ISSUE TITLE
Check and fix code to work with UTF8 encoding

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#14]
Fix this

**Comment by Clare2D** [comment]
Ok so now the encoding issues actually begin. There are a few pieces to the puzzle on this one. 

``` 
text$text <- gsub("start_year+10",start_year+10,text$text,fixed=T)
Error in gsub("start_year+10", start_year + 10, text$text, fixed = T) : 
  input string 433 is invalid UTF-8
```
where 
```
template <- readLines(paste0(getwd(),"/Templates/",templateversion,".tex"),encoding = "UTF-8")
```
and text$text[433]
```
"\t\t\\textbf{The alignment graphs below show the alignment of selected power technologies in the corporate bond portfolio relative to the IEA transition scenarios: B2DS (well below 2�C), SDS (2�C), NPS (4�C), CPS (6�C) and the bond market.}"
```
Which is saved in texstudio with a default save setting of UTF8. 
I can remove the "encoding ="UTF-8" but then the report doesn't print. ie fails at a later point. 
Do I need to change the ° symbol then in the latex template to something more utf8 compatible then... ? 
Would appreciate any thoughts.

**Comment by cjyetman** [comment]
where can I find `/Templates/`?

**Comment by Clare2D** [comment]
Hmm it is the submodule of Templates, however I'm not able to commit it somehow... not sure why not 
 
git submodule add https://github.com/Clare2D/Templates

**Comment by Clare2D** [comment]
This was the code.. Not sure this needs to be resolved. The files were all added, but maybe it has just been copied not properly cloned or whatever.. 
```
$ git submodule add https://github.com/Clare2D/Templates
Cloning into 'C:/Users/clare/Desktop/TestGit/PACTA_analysis/Templates'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 2761 (delta 73), reused 84 (delta 40), pack-reused 2638 eceiving objects: 100% (2761/2761), 286.41 M
Receiving objects: 100% (2761/2761), 287.97 MiB | 5.77 MiB/s, done.

Resolving deltas: 100% (1456/1456), done.
fatal: Unable to create 'C:/Users/clare/Desktop/TestGit/PACTA_analysis/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Failed to add submodule 'Templates'
```

**Comment by cjyetman** [comment]
Do you know *which* template caused that encoding message?

can you try this...
```r
# https://github.com/2DegreesInvesting/Templates/blob/master/GeneralTemplateInput_v6.tex
url <- 'https://raw.githubusercontent.com/2DegreesInvesting/Templates/master/GeneralTemplateInput_v6.tex?token=AANBGSFRAOPFCQ46EBCSJNC6SBK5G'
temp <- tempfile(fileext = '.tex')
download.file(url, temp)
template <- readLines(temp, encoding = 'UTF-8')
unlink(temp)
template[[504]]
# [1] "\t\t\\textbf{The alignment graphs below show the alignment of selected power technologies in the corporate bond portfolio relative to the IEA transition scenarios: B2DS (well below 2°C), SDS (2°C), NPS (4°C), CPS (6°C) and the bond market.}"
```

**Comment by cjyetman** [comment]
The above code works for me on macOS, Ubuntu linux, and Windows 10 (locale 1252), so I suspect it's a certain `.tex` file that was not created/encoded properly.

**Comment by Clare2D** [comment]
Thanks CJ. This worked on my machine as well. I'll see whether there is something I need to change.. I did change the degrees to UT..... text, but I don' think I pushed that, so it seems like this is better..

**Comment by Clare2D** [comment]
so that was wishful thinking that it was better... 

Trying to trace this back. 

1. template is created in texstudio where the automatic encoding is set to UTF-8
![image](https://user-images.githubusercontent.com/32903584/78874694-1022ad80-7a4d-11ea-8a25-2b5a5078f675.png)

2. template is read into Rstudio with either encoding or no encoding... 
```
template <- readLines(paste0(getwd(),"/Templates/",templateversion,".tex")) #,encoding = "UTF-8"
```
Sample output WITH encoding= "utf-8"
```
template[129]
[1] "\t\t\\Huge{\\textbf{AN\xc1LISIS DE ESCENARIOS}}\\\\[10pt]"
```
Sample output encoding NOT DEFINED
```
template[129]
[1] "\t\t\\Huge{\\textbf{ANÁLISIS DE ESCENARIOS}}\\\\[10pt]"
```
So I guess this is an issue, that the tex file is STILL not being saved with UTF-8 right? Or it's being saved with UTF-8 but when it's read in that doesn't display the utf-8 characters? 

3. There is then a different document created that is specific to the portfolio. I define the encoding here as UTF-8
```
write.table(text,paste0(report_path,ReportName,".Rnw"),col.names = FALSE,row.names = FALSE,quote=FALSE, fileEncoding="UTF-8")
```
4. When I knit2pdf I get this warning msg. The report prints but with obvious encoding issues.
```
Warning messages:
1: In knit(input, output = output, envir = envir, quiet = quiet) :
  The file "C:/Users/clare/Dropbox (2° Investing)/PortCheck_v2/10_Projects/SFC_2019_jackson/50_Outputs/COLFONDOS S.A. PENSIONES Y CESANTIAS//P. obligatorias/REP_SDS_POR_GLO_GLO_ES_2019/ClimateAlignmentReport_COLFONDOSS.A.PENSI_P.obligatorias.Rnw" must be encoded in UTF-8. Please see https://yihui.org/en/2018/11/biggest-regret-knitr/ for more info.
```
![image](https://user-images.githubusercontent.com/32903584/78892816-53d7e000-7a6a-11ea-86b3-3d984088f1b2.png)
Where the squares are an Á. 

So it seems the issue could still be at the tex level... But I don't know how to specifically save as utf-8

**Comment by cjyetman** [comment]
Can you give me a specific TEX file that you have this issue with so that I can investigate?

**Comment by Clare2D** [comment]
https://github.com/2DegreesInvesting/Templates/blob/master/GeneralTemplateInput_v6_SB_ES.tex
This one for example. 
Thanks

**Comment by cjyetman** [comment]
I was unable to get a setup that is able to compile that TEX file, aside from the encoding problem. I tried on my macOS (10.15.4), RStudio Cloud (Ubuntu 16.04.6 LTS), and a Windows 10 virtual machine.

@Clare2D can you try running the following code on your machine (in the Templates repo, or at least with the `GeneralTemplateInput_v6_SB_ES.tex` file in your working directory) and report the results...
```r
Sys.getlocale()
grep('UTF-8', iconvlist(), value = TRUE)

readr::guess_encoding('GeneralTemplateInput_v6_SB_ES.tex', n_max = -1)

text_utf8 <- readLines('GeneralTemplateInput_v6_SB_ES.tex', encoding = 'UTF-8')
text_utf8[129]
Encoding(text_utf8[129])

write.table(text_utf8, 'test_utf8_utf8.Rnw', col.names = FALSE, 
            row.names = FALSE, quote = FALSE, fileEncoding = 'UTF-8')
knitr::knit2pdf('test_utf8_utf8.Rnw')

write.table(text_utf8, 'test_utf8_native.Rnw', col.names = FALSE, 
            row.names = FALSE, quote = FALSE)
knitr::knit2pdf('test_utf8_native.Rnw')

text_native <- readLines('GeneralTemplateInput_v6_SB_ES.tex')
text_native[129]
Encoding(text_native[129])

write.table(text_native, 'text_native_utf8.Rnw', col.names = FALSE, 
            row.names = FALSE, quote = FALSE, fileEncoding = 'UTF-8')
knitr::knit2pdf('text_native_utf8.Rnw')

write.table(text_native, 'text_native_native.Rnw', col.names = FALSE, 
            row.names = FALSE, quote = FALSE)
knitr::knit2pdf('text_native_native.Rnw')
```

**Comment by cjyetman** [comment]
Can you also try this please and let me know the result...
```r
getOption('encoding')

text_utf8 <- readLines('GeneralTemplateInput_v6_SB_ES.tex', encoding = 'UTF-8')
text_utf8[129]
substr(text_utf8[129], 19, 19)
charToRaw(substr(text_utf8[129], 19, 19))

text_native <- readLines('GeneralTemplateInput_v6_SB_ES.tex')
text_native[129]
substr(text_native[129], 19, 19)
charToRaw(substr(text_native[129], 19, 19))
```

And for the record, I **think** this is the most correct, most explicit, most OS-portable (i.e. should also work on Windows) way to write a UTF-8 text file...
```r
text_utf8 <- readLines('GeneralTemplateInput_v6_SB_ES.tex', encoding = 'UTF-8')

con <- file('test_utf8_bytes.Rnw', encoding = 'native.enc')
writeLines(enc2utf8(text_utf8), con = con, useBytes = TRUE, sep = '\n')
close(con)

knitr::knit2pdf('test_utf8_bytes.Rnw')
```

**Comment by Clare2D** [comment]
So unfortunately, no successful results. 

```
readr::guess_encoding('GeneralTemplateInput_v6_SB_ES.tex', n_max = -1)
# A tibble: 3 x 2
  encoding     confidence
  <chr>             <dbl>
1 UTF-8              1   
2 windows-1252       0.46
3 windows-1250       0.27
```
text_native_native & text_native_utf8
![grafik](https://user-images.githubusercontent.com/32903584/79215127-82c7ca80-7e4b-11ea-8dbe-8c946cc3a472.png)

text_utf8_native &  text_utf8_utf8
![grafik](https://user-images.githubusercontent.com/32903584/79215285-a25ef300-7e4b-11ea-8c6c-415882219160.png)

There was a slight change to the file so 129 isn't the critical line anymore, however it didn't work on line 130 which is the line that has the first rouge character, so I wasn't able to get the code below to work: 

```
text_utf8 <- readLines('GeneralTemplateInput_v6_SB_ES.tex', encoding = 'UTF-8')
text_utf8[129]
substr(text_utf8[129], 19, 19)
charToRaw(substr(text_utf8[129], 19, 19))

text_native <- readLines('GeneralTemplateInput_v6_SB_ES.tex')
text_native[129]
substr(text_native[129], 19, 19)
charToRaw(substr(text_native[129], 19, 19))
```

```
text_utf8 <- readLines('GeneralTemplateInput_v6_SB_ES.tex', encoding = 'UTF-8')
> text_utf8[130]
[1] "\t\t\\Huge{\\textbf{AN\xc1LISIS DE ESCENARIOS}}\\\\[10pt]"
> substr(text_utf8[130], 19, 19)
Error in substr(text_utf8[130], 19, 19) : 
  invalid multibyte string, element 1
> charToRaw(substr(text_utf8[130], 19, 19))
Error in substr(text_utf8[130], 19, 19) : 
  invalid multibyte string, element 1
> 
> text_native <- readLines('GeneralTemplateInput_v6_SB_ES.tex')
> text_native[129]
[1] "\t\t\\node[below = 4.5cm, left= 1.0cm, right,align = left, white, text width=12cm](TN) at (current page.center){"
> substr(text_native[129], 19, 19)
[1] "5"
> charToRaw(substr(text_native[129], 19, 19))
[1] 35
```

I also tried the final solution, but need to investigate what's going on further there. 
```
> knitr::knit2pdf('test_utf8_bytes.Rnw', compiler = "xelatex")


processing file: test_utf8_bytes.Rnw
  |...........................................................................................................| 100%
  ordinary text without R code


output file: test_utf8_bytes.tex

! File ended while scanning use of \textbf .
<inserted text> 
                \par 
<*> ./test_utf8_bytes.tex

Error: LaTeX failed to compile test_utf8_bytes.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test_utf8_bytes.log for more info.
In addition: Warning message:
In readLines(input, encoding = "UTF-8", warn = FALSE) :
  invalid input found on input connection 'test_utf8_bytes.Rnw'
```

Thanks for this. Perhaps I investigate this final stage a bit further as a potential solution.

**Comment by Clare2D** [comment]
The problem in the last file as to why it doesn't work - the file stops writing the text after the character that requires encoding. ie the final two lines are:```
		\node[below = 4.5cm, left= 1.0cm, right,align = left, white, text width=12cm](TN) at (current page.center){
		\Huge{\textbf{AN
```

**Comment by cjyetman** [comment]
After lots of experimenting, discussing, reading, etc... I think the best solution is to make sure that `getOption('encoding') == "native.enc"` is `TRUE`, then following my suggestions above, things seem to work as expected. With `getOption('encoding') == "UTF-8"`, it would be possible to work around these problems by temporarily setting `getOption('encoding') == "native.enc"` before reading or writing and then setting it back after it's done. That could be wrapped in a function to make it easier, like...
```r
read_utf8_tex <-
  function(file) {
    opts <- options(encoding = "native.enc")
    on.exit(options(opts), add = TRUE)
    
    readLines(file, encoding = 'UTF-8')
  }

write_utf8_rnw <-
  function(text, file) {
    opts <- options(encoding = "native.enc")
    on.exit(options(opts), add = TRUE)
    
    con <- file(file, encoding = 'native.enc')
    writeLines(enc2utf8(text), con = con, useBytes = TRUE, sep = '\n')
    close(con)
  }
```

**Comment by Clare2D** [comment]
This seems to have solved everything. Thanks CJ. 
The only thing I had to change was that 
```
writeLines(enc2utf8(text), con = con, useBytes = TRUE, sep = '\n')
```` 
became
```
writeLines(enc2utf8(text$text), con = con, useBytes = TRUE, sep = '\n')
```
because text itself is a list. I guess there is a slightly neater solution here...
