### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#144]
The code base is contained with dead code. Removing dead code
is a safe way to improve the code base -- it does not affect the 
behavior of the code, and results in cleaner code where the 
important stuff is easier to see.

https://refactoring.com/catalog/removeDeadCode.html

**Comment by cjyetman** [comment]
@maurolepore how do we track if/when this issue has been resolved completely?

**Comment by maurolepore** [comment]
Good point. I think we should close it, and just try remove dead code as we see it — or at least to try minimise the ones we comment out code
