### ISSUE TITLE
How should we go about updating the upstream Dockerfile?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#180]
@jacobvjk, thanks for getting us the upstream Dockerfile of the base image. @cjyetman and @AlexAxthelm noted that it's crucial to test locally with the same environment where the web tool will eventually run. 

### How should we go about extending the base image? 

For example, we need to install the packages we use, and maybe install other software (e.g. RStudio Server to make it easy to debug the web tool when we run it in docker).

We can extend it ourselves but we need a system to ensure transition monitor is in sync. Do you already have such a system or should we engage Wilhelm Schürmann (con-wbsch) in this conversation?

**Comment by jacobvjk** [comment]
@maurolepore @cjyetman @AlexAxthelm I will check in with @Clare2D as I haven't worked on the transition monitor myself. So I am not aware of any systems that keep it in sync. Will get back t you asap

**Comment by maurolepore** [comment]
Thanks! Ideally, we would collaborate with them in a single repository. I now forked the source repo so we could submit our changes as a PR. And when they merge the PR, Docker Hub will automatically rebuild the image and we can pull it locally or on a CI pipeline.

@AlexAxthelm, do we have an account on DockerHub? Shall I create a new one?

**Comment by AlexAxthelm** [comment]
https://hub.docker.com/orgs/2dii

**Comment by cjyetman** [comment]
I created an issue at Constructiva/Wim’s docker build repo: https://github.com/con-wbsch/2diidockerrunner/issues/1

hopefully that will help making changes there a lot faster

**Comment by cjyetman** [comment]
Sorry if this is out of line @maurolepore, but I think the draft PR #164 is at least related to this, though it may not address everything on topic here

**Comment by maurolepore** [comment]
Thanks! Yeah -- I have to catch up with that PR but indeed its' related. Thanks.

**Comment by cjyetman** [comment]
closing this because https://hub.docker.com/r/2dii/r-packages seems to serve our purposes here pretty well, and further development of the docker image happens over there
