### ISSUE TITLE
Remove plyr

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#184]
Relates to #137 

plyr is superseded by dplyr. We seem to only use one function from plyr: `mapvalues()`. Here is how we can
replace it:

``` r
char_vec <- sample(c("a", "b", "c"), 10, replace = TRUE)

from <- c("a", "b")
to <-  c("Apple", "Banana")
identical(
  plyr::mapvalues(char_vec, from, to),
  dplyr::recode(char_vec, !!!setNames(to, from))
)
#> [1] TRUE

# Other options
identical(
  plyr::mapvalues(char_vec, c("a", "b"), c("Apple", "Banana")),
  dplyr::recode(char_vec, a = "Apple", b = "Banana")
)
#> [1] TRUE

identical(
  plyr::mapvalues(char_vec, c("a", "b"), c("Apple", "Banana")),
  dplyr::case_when(
    char_vec == "a" ~ "Apple", 
    char_vec == "b" ~ "Banana",
    TRUE ~ char_vec
  )
)
#> [1] TRUE
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

--

Searching for `[^d]dplyr`:

<img src=https://user-images.githubusercontent.com/5856545/95796738-49193480-0cb3-11eb-9b9d-850e9e1d5f11.png width=500>

@jacobvjk, can we remove this function? If I remove it the integration test continues to pass (at least locally).

```r
CarstenMetricChart <- function(plotnumber, chart_type, explicit_filename = "") { ...
```

**Comment by jacobvjk** [comment]
@maurolepore yes please, let's get rid of it

**Comment by maurolepore** [comment]
> Anything in 0_graphing_functions can be ignored as this will be supersceded
-- https://github.com/2DegreesInvesting/PACTA_analysis/pull/183#discussion_r503717065

**Comment by maurolepore** [comment]
@cjyetman, I see #196 removed plyr from `use_r_packages()` but I still see [this](https://github.com/2DegreesInvesting/PACTA_analysis/blob/bb1c3a13af0de2b351ca06ebe74460269422b08b/0_graphing_functions.R#L3350):

```r
    port$portfolio_name <- plyr::mapvalues(port$portfolio_name, c(portfolio_name_select, cb_market_ref), c("Portfolio", cb_market_ref))
```

I think you intentionally focused on packages we need for the web tool, right?

Can you share the code you use for detecting the relevant packages? Maybe in R/utils.R?

**Comment by cjyetman** [comment]
Yes, exactly. I specifically ignored any dependencies that **only** appeared in [0_graphing_functions.R](https://github.com/2DegreesInvesting/PACTA_analysis/blob/bb1c3a13af0de2b351ca06ebe74460269422b08b/0_graphing_functions.R)

this is the code I used (after temporarily deleting 0_graphing_functions.R and deduplicate/load-and-attach-r-packages.R)
```
pkgs_used <-
  sort(unique(c(
    requirements:::req_dir(),
    requirements:::req_dir("../create_interactive_report/"),
    requirements:::req_dir("../StressTestingModelDev/")
    )))

pkgs_used <- setdiff(pkgs_used, c("base", "grid", "tools", "utils"))
pkgs_used <- setdiff(pkgs_used, c("PACTA.analysis", "r2dii.utils"))

cat(paste0('install.packages(c("', paste(pkgs_used, collapse = '", "'), '"))'))
```

**Comment by cjyetman** [comment]
The `dplyr` (rough) equivalent to `plyr::mapvalues ` is `dplyr::recode`

these return the same thing...
``` r
plyr::mapvalues(x = c("a", "b", "c"), from = c("a", "c"), to = c("A", "C"))
dplyr::recode(.x = c("a", "b", "c"), "a" = "A", "c" = "C")
```

or if you 'pre-process' the arguments, it could look like this...
``` r
x <- c("a", "b", "c")
from <- c("a", "c")
to <- c("A", "C")

plyr::mapvalues(x, from, to)
dplyr::recode(x, !!!setNames(to, from))
```

or if you did further pre-processing of the `to` and `from` values, it could look like this...
``` r
name_recodes <- setNames(to, from)
name_recodes
dplyr::recode(x, !!!name_recodes)
```

so, one could replace the existing line like this...
``` r
# old with plyr::map mapvalues
port$portfolio_name <- plyr::mapvalues(port$portfolio_name, c(portfolio_name_select, cb_market_ref), c("Portfolio", cb_market_ref))

# new with dplyr::recode
name_recodes <- setNames(c("Portfolio", cb_market_ref), c(portfolio_name_select, cb_market_ref))
port$portfolio_name <- dplyr::recode(port$portfolio_name, !!!name_recodes)
```

**PLEASE do not take my word for it and carefully test this if you want to make this change.**

Also be aware, if the vector to be changed is a **factor vector**, you would **need to use dplyr::recode_factor** and **the syntax would be different**.

**Comment by cjyetman** [comment]
these seem to be the only exiting uses of `plyr::mapvalues()`
https://github.com/2DegreesInvesting/PACTA_analysis/blob/1d4cc3ce518eeb416a3b2424215edef3a58741df/0_graphing_functions.R#L3350
https://github.com/2DegreesInvesting/PACTA_analysis/blob/1d4cc3ce518eeb416a3b2424215edef3a58741df/0_graphing_functions.R#L3369

**Comment by maurolepore** [comment]
I think we should close this as it looks like it's too much work for something we don't care about. I'd rather use the effort elsewhere. 

https://github.com/2DegreesInvesting/PACTA_analysis/issues/184#issuecomment-707666948 suggests we should not put a lot of energy here. And a lot of energy seems what we need to do this change safely. CJ highlights the proposed change works for characters but not factors, but I see the script does make the working vector to a factor.

**Comment by maurolepore** [comment]
Hopefefully soon we'll have tests covering the web tool ecosystem and then we'll be able to remove the entire file and see if we trully don't need it.
