### ISSUE TITLE
library calls in integration test

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#194]
In this chunk in the integration test, a bunch of packages are loaded. Are all these packages needed for the Docker image then? Should these be loaded using `use_r_packages()` instead, or are some of these only for dev purposes?

```{r}
library(purrr)
library(devtools)
library(testthat)
library(config)
library(rlang)
library(renv)
library(glue)
library(fs)
library(here)
library(conflicted)

devtools::load_all()
resolve_conflicts()
```

**Comment by maurolepore** [comment]
Good point. Here is one idea. What do you think?

We could keep `use_r_packages()` focused on "production" packages -- those strictly necessary for the web tool, i.e. the ones that should be included in the the docker image that runs the web-tool in production.

On top of that, we could use packages for testing and for development -- like the ones listed here. And we could add them to a layer in our own docker containers via a Dockerfile that transition monitor needs not to have.

**Comment by cjyetman** [comment]
👍 to all that!

**Comment by maurolepore** [comment]
Closing this as the integration test file is gone.
