### ISSUE TITLE
different way of loading many packages

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#201]
just a suggestion...

would something like this be easier to parse the necessary package names from (in comparison to the existing [deduplicate/load-and-attach-r-packages.R](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/deduplicate/load-and-attach-r-packages.R))

``` r
pkgs_to_load <- 
  c(
    "assertthat", 
    "bookdown", 
    "config",
    "conflicted",
    "countrycode"
    )

lapply(pkgs_to_load, library, character.only = TRUE, quietly = TRUE)
```

**Comment by maurolepore** [comment]
Yes, I like this because then we can reuse `pkgs_to_load` to update the Dockerfile. Do you want to submit a PR or should I do it?

Relates to https://github.com/2DegreesInvesting/PACTA_analysis/issues/199

**Comment by cjyetman** [comment]
you do it... so that it can integrate with your code on the other end in the same PR

**Comment by cjyetman** [comment]
this is somewhat related to #199

**Comment by maurolepore** [comment]
WIP

**Comment by Clare2D** [comment]
Did this get resolved?

**Comment by maurolepore** [comment]
No, I think this is still pendent. It's a non crucial enhancement so I would do it after the upcoming release.

**Comment by maurolepore** [comment]
Also, I would be okay closing now and revisiting the idea later. There are other more robust ways to declare the r packages on which a project depends (e.g. via renv or DESCRIPTION: Imports).

**Comment by maurolepore** [comment]
I'm closing this because I now realize that I often run a global search for "library" to quickly discover which packages the project uses (unless it's an R package in which case I read DESCRIPTION).

![image](https://user-images.githubusercontent.com/5856545/99845308-0b24f100-2b3a-11eb-8740-4d76983cba87.png)
