### ISSUE TITLE
need an automated testing regime

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#245]
need an automated testing regime that runs the web tools on a set of representative example portfolios. this should probably be something that runs offline, **not** something that runs through the automated CI on GitHub because the sample portfolios may be large and/or private (though the testing infrastructure can/should be committed to the master repo)

@Clare2D will provide the sample portfolios
@cjyetman will develop the testing infratsructure

**Comment by Clare2D** [comment]
Will get to these tomorrow morning

**Comment by cjyetman** [comment]
@jacobvjk prepared some sample portfolios to test various edges cases that are stored here
`~/Dropbox (2° Investing)/2° Investing Team/People/Jacob/p2020_test_cases`

**Comment by cjyetman** [comment]
status update: My testing infrastructure in #265 is working pretty good by now, at least in the sense that it's doing what it's supposed to do. Of the 12 sample cases @jacobvjk prepared, 3 out of 12 can run through the test without error (dependent on a number of bugs fixes / PRs listed in the first comment of #265). That doesn't sound great, but all of those bugs were revealed by running the tests multiple times, so... it's doing what it's supposed to, it's just a bit tedious hunting down the cause of each error. But anyway, I'm making progress, and eventually I'll figure out all the reasons the other 9 sample cases can currently not complete.

**Comment by Clare2D** [comment]
Thanks. I'll go through any open issues now, but happy to look at some together if that helps.
