### ISSUE TITLE
Relative vs Absolute file paths

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#246]
I'm having an issue loading in a json file from a relative file path

```config <- jsonlite::read_json(paste0(real_estate_dir,"/data/config.json"))
config <- jsonlite::read_json(paste0("C:/Users/clare/Desktop/Git/user_results/CHPA2020/real_estate","/data/config.json"))
```
The first option doesn't work, while the second does:
While they should be referring to the same location. 
```
real_estate_dir
../user_results/CHPA2020/real_estate

getwd()
[1] "C:/Users/clare/Desktop/Git/PACTA_analysis"
```

Any ideas? @cjyetman

**Comment by cjyetman** [comment]
to be clear...

if this is the first option
`config <- jsonlite::read_json(paste0("C:/Users/clare/Desktop/Git/user_results/CHPA2020/real_estate","/data/config.json"))`
that's an absolute path... is that working?

this would be the equivalent relative path, given that `getwd()` gives `[1] "C:/Users/clare/Desktop/Git/PACTA_analysis"`
`config <- jsonlite::read_json(paste0("../user_results/CHPA2020/real_estate", "/data/config.json"))`
that does not work?

can you remove the `paste0` to eliminate anything that might cause a problem... what is the result of this?
```
getwd()
jsonlite::read_json("C:/Users/clare/Desktop/Git/user_results/CHPA2020/real_estate/data/config.json")
jsonlite::read_json("../user_results/CHPA2020/real_estate/data/config.json")
```

**Comment by Clare2D** [comment]
The first one works, it's the relative one that doesn't..

**Comment by cjyetman** [comment]
and the result of running these three line together?
``` r
getwd()
jsonlite::read_json("C:/Users/clare/Desktop/Git/user_results/CHPA2020/real_estate/data/config.json")
jsonlite::read_json("../user_results/CHPA2020/real_estate/data/config.json")
```

**Comment by Clare2D** [comment]
Ok it seems I'm in a different dir to what I thought! Sorry!
