### ISSUE TITLE
Remove diff between  NPR and NPSRTS

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#248]
This should only be one scenario. With the addition of HDV to Automotive as NPS and all teh LDVs as NPSRTS, this may create problems down the line

fyi @Clare2D

**Comment by Clare2D** [comment]
This should be done in the latest data release. This just needs to be uploaded to the pacta-data folder

**Comment by jacobvjk** [comment]
before we do that, I would weant to check if that affects the stress test. Could cause issues over there as well
