### ISSUE TITLE
new latex pkgs

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#266]
changes to a latex file [here](https://github.com/2DegreesInvesting/create_interactive_report/commit/79b0570cd7fc1bb90fc06fc7f824f0c3e311208c) and [here](https://github.com/2DegreesInvesting/create_interactive_report/commit/fb06eca6ceb1b444ea1ab34cde7fa23bc0718d64) will likely add new errors and/or warnings when running the web tool/s, and we will probably need to add all the new latex packages to the [docker image](https://github.com/2DegreesInvesting/2diidockerrunner/blob/master/r-packages/Dockerfile)

**Comment by maurolepore** [comment]
I have no experience with latex but happy to add the required dependencies to system/Dockerfile and r-packages/Dockerfile. Can @cjyetman, @Clare2D or someone else comment here which are the dependencies at the system level (suff to install with `apt-get install`) and which are the required R packages (stuff to install with `install.packages()`)?

BTW, those Dockerfiles live not here but in https://github.com/2DegreesInvesting/2diidockerrunner. Should we move this issue there?

**Comment by cjyetman** [comment]
1. Yes
2. I asked myself the same question, but since they are certainly only relevant to latex I thought maybe they shouldn't be in a broader oriented, system/only image. 🤷‍♂
