### ISSUE TITLE
install pandoc in .github/workflows/test-r-scripts.yaml

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#267]
Follow up https://github.com/2DegreesInvesting/PACTA_analysis/pull/261#issuecomment-716809041

**Comment by cjyetman** [comment]
this could possibly be resolved by using the suggestion in #269 to import the [2DegreesInvesting/2diidockerrunner/r-packages/Dockerfile](https://github.com/2DegreesInvesting/2diidockerrunner/blob/master/r-packages/Dockerfile) image to run the action/workflow

**Comment by maurolepore** [comment]
Closed by #299
