### ISSUE TITLE
add unit to Equity_results_map.rda

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#27]

**Comment by cjyetman** [comment]
also add Carsten metric (make sure the regional weighting is included) to Bonds_results_map.rda

**Comment by Clare2D** [comment]
So this is not as trivial as thought. There is no plan_carsten at the regional level so we basically can't do this without a complete rewrite of many things... 
We need a slight rethink here.

**Comment by cjyetman** [comment]
Maybe (in my case anyway) we just show the map for equity and not bonds then? @2diiKlaus?

**Comment by Clare2D** [comment]
The units are in here now anyway. Just no plan_carsten. So it's also a question of whether show the production values make sense when applying the portfolio weight approach. We do use them in the trajectory charts so I would suggest we just use the plan_alloc_tech_prod.
