### ISSUE TITLE
Remove filter for small EQ holdings

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#309]
https://github.com/2DegreesInvesting/PACTA_analysis/blob/0e03b064dba89bbb69cd636b75aec1a35eaee41a/3_run_analysis.R#L37

We introduced this filter as a hack to get rid of some duplicate values, which are now handled more appropriately via a dedicated list of duplicate ISINs.

This filter should be removed, as it can in specific cases lead to valid equity holdings being excluded from the analysis. This was the case for EIOPA, when splitting the portfolio up into a large number of subgroups. While that is not a very common case, there is no reason for this to stay in the code and be a hazard for other future applications

fyi @Clare2D

**Comment by jacobvjk** [comment]
also: this is not an issue in P2020, as the filter is not set there

**Comment by Clare2D** [comment]
Just want to clarify that this was removed to allow the code to run faster and not hit memory issues rather than to remove the duplicates!

**Comment by jacobvjk** [comment]
Okay, good you pointed that out. We can discuss this tomorrow after the deadline if you want
