### ISSUE TITLE
Make input file path more precise (include actual pf name)

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#322]
https://github.com/2DegreesInvesting/PACTA_analysis/blob/5919cd35d3390900a63c926a4ce948f4ff6aab9e/0_web_functions.R#L170

This is legacy code that loops over the input portfolios instead of specifically naming the required file.
While this is okay, as long as there is only one portfolio in the directory, it can create errors when there is more than one portfolio.
In the initial version, this is not expected to happen, but it seems like a big vulnerability going forward

fyi @cjyetman @Clare2D

**Comment by Clare2D** [comment]
This was resolved
