### ISSUE TITLE
Fund Coverage

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#329]
There seems to be a large difference in fund coverage for investors between the meta report and individual portfolio reports

@jacobvjk  are you able to discuss this with @fiona511 to ensure the correct file was uploaded and that this worked?

**Comment by jacobvjk** [comment]
sure @Clare2D will check

**Comment by jacobvjk** [comment]
Coverage table will be changed to pull all fund categories to the top level, which reflects what is happening in the data.
New categories are:

Funds - Unknown (direct)
Funds - Equity (indirect)
Funds - Corporate Bonds (indirect)
Funds - Other (indirect)

will open additional issue for the definition of the Flag
