### ISSUE TITLE
Add the renewables build out data and chart

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#33]
We need to update the code for the renewables build out chart to work with the new data and be ready to include in the SFC reports. 
Vincent are you able to have a look at this? Some point in the next 2 weeks? The code is in the data_preparation repo

**Comment by vintented** [comment]
@Clare2D sounds good to me. Do you mind sharing the existing chart or what you envisioned? Also, do we want to include the technology_type breakdown or should it be just renewables aggregate?

**Comment by Clare2D** [comment]
Ok, so checking out the code and the graphs and there are two charts necessary, the data for which is created in the single function in 9_data_import (data_prep repo) dataprep.CoalRet.REadd()
this creates two files, that should bot be saved in analysis_inputs_path 

readRDS(paste0(analysis_inputs_path, "/CoalRetirementsData.rda"))
readRDS(paste0(Location,"ReferenceData/RenewablesAdditionsData.rda"))

The two charts already have graphing code 
-RenewableAdditionsChart  line 2987 of graphing_functions 
- CoalRetirementChart @3431

This is now for two charts, but it's primarily about the data preparation which is happening in the same function. 
Thanks Vincent. 


![62_REP_SDS_POR_GLO_GLO_EN_2019](https://user-images.githubusercontent.com/32903584/81266022-56672e80-9044-11ea-8e55-f7f6df83944b.png)


![64_REP_SDS_POR_GLO_GLO_EN_2019](https://user-images.githubusercontent.com/32903584/81265617-b6a9a080-9043-11ea-8d38-40c9c681b0d0.png)
