### ISSUE TITLE
BUG: Flag "Included in analysis" falsely includes unmatched funds

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#330]
The definition of the flag only excludes funds, for which no bloomberg data could be found.
Since we get fund info via Lipper now, this definition should be updated somehow to clarify that unmatched funds (essentially funds whose ISINs are not in the fund_data) are NOT included in the analysis

fyi @Clare2D @fiona511

**Comment by cjyetman** [comment]
I assume this is largely related to #368?

**Comment by Clare2D** [comment]
I believe so yes! Or is resolved anyway.
