### ISSUE TITLE
sum needs a na.rm=TRUE

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#336]
need to add a `na.rm = TRUE` to the `sum` command...
https://github.com/2DegreesInvesting/PACTA_analysis/blob/0408aa00cd86746561b6a5567356ddf52d219d92/0_portfolio_test.R#L69

personally, I don't know the context of this, but working with @Clare2D and @fiona511 to get large meta-reports run, it has become pretty clear that this is needed

**Comment by Clare2D** [comment]
Basically, if a NA value comes through in the MarketValue and there is another of the same ISIN this will cause all exposure to this ISIN to drop to NA as well.
