### ISSUE TITLE
Corporate Bond Sector Split

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#36]
As I am fixing the error regarding the linkage of asset level data with corporate bond tickers, I'm wondering whether we could implement a "debt split" similar to a revenue breakdown as per equity. Given that the data comes separated by bics_sector already, we could use this to link the debt to the specific sector that it is related to. 

This could more or less be implemented like in the Revenue split methodology - creating multiple lines per debt ticker and aggregating from there. 

My initial questions:
- Is this debt split actually reflective of where debt is being used?
- What am I missing here?
Anyway, need to turn this around quite quickly (ie tomorrow) so would appreciate a quick response. We already have this data from Bloomberg.

**Comment by Clare2D** [comment]
@Lauramirez-2ii FYI

**Comment by Lauramirez-2ii** [comment]
sounds like a nice thing to have
