### ISSUE TITLE
New config variable required in stress test

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#367]
The stress test scripts now require a config object price_data_version, which is currently hard coded in the corresponding web tool scripts, to ensure the correct price data is used for the running pacta 2020 project. As soon as we calculate new ones though (e.g. Austria), this should be set on a project by project level.

- Pass a config variable `price_data_version` to the stress test function in script 2
- the variable must follow: YYYYQQ, i.e. `price_data_version: 2020Q4` or `price_data_version: 2021Q1` if added to some config.yml

fyi @Clare2D

**Comment by cjyetman** [comment]
@jacobvjk is this closed by 2DegreesInvesting/StressTestingModelDev/pull/164 or is there still something to be done on the PACTA side?

**Comment by jacobvjk** [comment]
This is done @cjyetman
