### ISSUE TITLE
Redefine fund processing

### ISSUE THREAD

**Issue by andybue** [2DegreesInvesting/PACTA_analysis#368]
general remark: After the evaluation users want to know the coverage of the funds that have been listed in the portfolio. this is tricky right now,  as the information gets lost during evaluation. Currently information on fund coverage needs to be reconstructed. 

1. add_fund_portfolio, leaves no trace of initial fund as direct holding in the portfolios -> it is hard to access succesfully added fund in the final portfolio

2. add_fund_portfolio, does not include any information on the completness of the look through of the underlying lipper data   

3. The flags of the audit file and the function that creates Exhibit 1 in the report are not in sync (https://github.com/2DegreesInvesting/create_interactive_report/issues/345)

TODO:

1. Keep original Funds as direct holding in the total portfolios
2. Set market_value to "unknown" value and "original_value_usd" to original value. Succesfully implemented Funds have market_value  == 0. 
3. Coverage of Funds can be assessed by comparing original_value_usd and market_value
4. As this might be to hard to read, add additional file output: fund_results.rds, that summarizes the results of the fund portfolio.
5. Ensure that the solution is in sync with report generation

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by cjyetman** [comment]
@andybue is this closed by #378, or is that only a piece of what's described here?

**Comment by cjyetman** [comment]
@andybue after you're recent improvements in fund coverage, is this issue finally resolved?

**Comment by cjyetman** [comment]
pretty sure this has been resolved by #378 and 2DegreesInvesting/create_interactive_report/pull/372
