### ISSUE TITLE
Pass new config to stress test: price_data_version

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#369]
blocked by https://github.com/2DegreesInvesting/StressTestingModelDev/issues/177

For new iterations of PACTA2020/COP we should use the updated price data file for the stress test calculations. In order to not mess with past results, I have started versioning price data and will need information on which version to use in the future

Currently, all Pacta 2020 calculations use `price_data_version: 2020Q4`
The updated version is `2021Q1`. I would strongly encourage using that for future projects, as it's corrected trajectories will enable us to more confidently show results for different shock years.

Suggestion: add `price_data_version: YYYYQQ` to the project config.
for Switzerland and Liechtenstein set `2020Q4`, for all other `2021Q1` (what about Austria? is it already live?)

I would like to get your thoughts on this approach @Clare2D @cjyetman and if you are fine with that

**Comment by Clare2D** [comment]
I think we can add it in - set a default in the code in case an existing user reruns with an older parameter file and then it should be alright to continue.

**Comment by cjyetman** [comment]
sounds good to me!

**Comment by jacobvjk** [comment]
Given the fact that results that have already been shown to users should probably not change, that default probably should be 2020Q4. On the other hand, if we think it is likely that future users can be in the situation of running the analysis with an old parameter file (?), this would mean they get potentially worse/weird results @Clare2D

**Comment by Clare2D** [comment]
Yep, the default should be 2020Q4 so the old results do not change. Then we just need to ensure that the new value is in the parameter files so that the default is never triggered in new projects.
