### ISSUE TITLE
include lipper data in indentify funds

### ISSUE THREAD

**Issue by andybue** [2DegreesInvesting/PACTA_analysis#372]
currently, the funds are identified by bloomberg data by:
fund_portfolio <- portfolio %>% filter(asset_type == "Funds", !is.na(isin))

but, we also know which isins are funds from the lipper data, which is loaded as fund_data in the environment during the evaluation
unique(fund_portfolio_$isin)
would give the list of all fund_isin that we "know"

for two examples that i review (users 44, 149 in the Liechtenstein project) there is a fund (LU1808485178) in the lipper data that is not classified as funds in the bloomberg data: 

so i would suggest to 

fund_portfolio <- portfolio %>% filter((asset_type == "Funds" & !is.na(isin)) | is.element(isin, fund_data$fund_isin))

**Comment by andybue** [comment]
and ensure in a subsequent function that the asset_type of the line in the portfolio is adjusted to "Funds"

**Comment by cjyetman** [comment]
@andybue was this achieved in your recent PR to pacta_data?

**Comment by cjyetman** [comment]
I believe this was resolved by the combination of #391 and 2DegreesInvesting/pacta-data/pull/26
