### ISSUE TITLE
Remove text reference to the bar

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#375]
"Die folgende Tabelle fasst zusammen, welche Finanzinstrumente in die Analyse einbezogen werden. Der Balken zeigt den Anteil der von der PACTA-Analyse abgedeckten Anlageklassen am gesamten Portfolio."
We removed the bar.

**Comment by cjyetman** [comment]
@Clare2D should this be closed by #354?

**Comment by Clare2D** [comment]
Thanks, yes!
