### ISSUE TITLE
check the text about the emissions pie

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#376]
Not sure whether this makes complete sense: 

![image](https://user-images.githubusercontent.com/32903584/104158922-aaee5500-53ee-11eb-9b3b-1916c971a653.png)

where 

![image](https://user-images.githubusercontent.com/32903584/104158932-b3469000-53ee-11eb-8967-917fcabc4150.png)

Should it not say 6.8% is linked to this 81% of emissions?

**Comment by Clare2D** [comment]
![image](https://user-images.githubusercontent.com/32903584/104159124-0ae4fb80-53ef-11eb-9674-f973d3cf1170.png)
Yep reading the english - I think we've currently got the wrong value being referenced here and it should be changed to 81% or more generic text. What do you think @andybue?

**Comment by cjyetman** [comment]
that was my understanding of the intent of that chart

**Comment by cjyetman** [comment]
@Clare2D should this be closed due to the decision made in #354, or should this be left open to be resolved when we come up with a better solution?
