### ISSUE TITLE
reduce web tool scripts to relevant OS

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#392]
@maurolepore I think we should reduce the web tool scripts test/s so that they only run on the target OS, which is whatever OS our web server is running on. Running it on a variety of desktop OSs and old Linuxes seems irrelevant and a waste of time and resources since the web tool scripts are not really intended for those platforms.

**Comment by cjyetman** [comment]
closed by #399 

actually, we don't know precisely what OS is running on the web server, but it's a safe bet that it's Linux, and we're now running the web tools tests on a a modern, recent, popular flavor of Linux, so I think that's adequate for now.

**Comment by maurolepore** [comment]
This suggests that the server is running Ubuntu 18.04, right?

https://github.com/2DegreesInvesting/docker/blob/master/system/Dockerfile

**Comment by cjyetman** [comment]
hmmmm... so I was thinking, we don't actually know what OS the web server is running, but as you've pointed out it is obvious what OS the docker instance that the web server runs the web tool scripts inside of is running because we control that with our docker image... and that's much more relevant than what OS the web server is running anyway...

so yeah... whatever we have set in our docker image is what we should try to run our GitHub Action on here
