### ISSUE TITLE
web tool scripts are failing on latex compilation

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#393]
@maurolepore all but the macOS instance are failing the web tool scripts tests with..
```
Error: Error: LaTeX failed to compile
D:/a/PACTA_analysis/PACTA_analysis/PACTA_analysis/working_dir/50_Outputs/TestPortfolio_Input/executive_summary/template.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
```
https://github.com/2DegreesInvesting/PACTA_analysis/pull/391/checks?check_run_id=1908941675

I don't see any reason why this error would be caused by any recent changes in our code, so I assume it must be something with how the instance is being created.

**Comment by maurolepore** [comment]
I think we are good now. I'll close before I forget as I did not use the right keyword on the related PR.
