### ISSUE TITLE
Alternative save location for missing isins

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#413]
We need an altenative save location for missing ISINs we discover. We could save them in projects again, but need to be able to deduplicate easily. 

This step has always been unclear to me, and frankly still is now. It seems like this would require a user to create a PR any time something changes `data/isins_missing_bbg_data.csv`? If the goal is to continually expand a list of ISINs we've found "in the wild" but that are unknown in our data, that's great, but I think there's probably a much better, more realistic way of doing that... I think quite possibly the `PACTA_analysis` repo is **not** the right place for it.

Sorry, I know that here you're just trying to document the current process as it is.

_Originally posted by @cjyetman in https://github.com/2DegreesInvesting/PACTA_analysis/pull/412#discussion_r583492701_

**Comment by cjyetman** [comment]
@jdhoffa do you have thoughts on this?

My feeling is... for a given project/portfolio, the `30_Processed_Inputs/[PORTFOLIO_NAME]/invalidsecurities.csv` which is standard output for PACTA includes the necessary information to determine ISINs in that portfolio that were not identified, i.e. "missing" from our financial data, in which case, if we wanted to for a given project, we could easily get a list of unknown ISINs and and explore ways of filling that gap with BBG or other financial data provider. So this attempt to capture centrally all unknown ISINs every time PACTA is run anywhere by anyone is unnecessary and should be removed.

**Comment by jdhoffa** [comment]
1000000% agree! :D

**Comment by cjyetman** [comment]
👍🏻 perfect, so then the strategy to deal with this issue will be to remove `data/isins_missing_bbg_data.csv` and any code that references it or read/writes it

**Comment by jdhoffa** [comment]
i back that strategy!
