### ISSUE TITLE
remove test_test_cases.R

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#414]
I wrote `test_test_cases.R` last fall in the rush to get things working for the Swiss project. I think we should probably remove it because it has limited utility and may have fallen out of sync with the rest of the code anyway. Does anyone object to that?

@Clare2D @jacobvjk @maurolepore @MonikaFu @jdhoffa

**Comment by jacobvjk** [comment]
fine by me

**Comment by Clare2D** [comment]
Works for me too

**Comment by MonikaFu** [comment]
Fine by me. Would be nice to have some testing script in place, though

**Comment by maurolepore** [comment]
Good with me. You are the best to judge the usefulness of that file. 

Do you imagine any way that could somehow show someone else what kinds of things you look for? (Maybe recording your screen when you do it?)

**Comment by cjyetman** [comment]
what kinds of thing I look for when I'm doing what?

**Comment by maurolepore** [comment]
If I understand correctly the file you intend to remove reflects some tests you used to run just after you built a new image. The process of building the image is documented in the docker repo and in the demo you recorded, but AFAIK the tests you usually run are still undocumented, right?
That’s what I meant to say that  would be nice to have

**Comment by cjyetman** [comment]
This script is not related to that at all... It was originally meant to run a bunch of test portfolios through the PACTA process locally on my machine, manually... and evolved into what I used to manually create all the Swiss portfolios on the fly.

**Comment by maurolepore** [comment]
My bad. Sorry.

**Comment by cjyetman** [comment]
I'm still torn about what to do/where to put the files I use to test the Docker image. They have some private data, so can't be public. For now, they live on the "docker" folder on Constructiva's SFTP server in a file called `pacta_web_template_v0.0.9.zip`, because at some point I was convinced that these files were more for Constructiva's benefit to see how the docker image is intended to be used.... but I still use it as my default to test new docker images when I create them.
