### ISSUE TITLE
Create additional csv file results

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#427]
There is a JSON file written entitled invalidsecurities. We however need this same information in csv as well. Providing the user with the JSON file is not so useful! 

additionally, I think we should make the portfolio level results available. This is equity_results_portfolio and bonds_results_portfolio also as csv files.

**Comment by cjyetman** [comment]
@Clare2D do you know what the purpose of this function `export_audit_information_jsons()` is? I actually have no idea...

https://github.com/2DegreesInvesting/PACTA_analysis/blob/989375b6bf154c44ad9e695441b174893fdaf5d6/0_json_functions.R#L250-L278

My suggestion would be to modify the function name and purpose to `export_audit_information_data()` and then simultaneously export JSON and CSV files... does that make sense?

**Comment by Clare2D** [comment]
Yep that makes sense. The data that is created here is used by Wim for the first audit charts that he creates. But he just expects outputs so we can change the function name.
