### ISSUE TITLE
Evaluation of Required platform input file

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#429]
So, at the moment we required Investor.Name and Portfolio.Name, however what is happening on the website is that Investor.Name is being ignored and we're just using Portfolio.Name. The investor name used at the beginning of the report is being taken from the inputs that the user provides when signing up and stays that way for all portfolios a user uploads.

Similarly, if only a single portfolio is uploaded, the portfolio name is overwritten by whatever a user inputs, however if multiple portfolios exist in the file, then the name from the file is used. 

We can change this, we just need to coordinate on a solution for this.

**Comment by cjyetman** [comment]
Since we're moving in the direction of narrowing the scope of the core PACTA process so that portfolio name and investor name are irrelevant, I think this issue is no longer relevant.
