### ISSUE TITLE
DFS: clarify project code and stress test shock year in project parameter file

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#431]
depends on https://github.com/2DegreesInvesting/StressTestingModelDev/issues/274

We want to run the DFS analyses on the platform. This means the individual results will produce a stress test calculation.

For that to work, we need to set in the corresponding project parameter file
- the project code `PA2021DFS`
- the price data version `2021Q1`
- the shock year `2030`

fyi @cjyetman

**Comment by jacobvjk** [comment]
@cjyetman do you know who sets up these files? I don't think I can determine all the parameters that are required in the project parameters file to be.. `./parameter_files/ProjectParameters_PA2020DFS.yml`

**Comment by cjyetman** [comment]
I'm not 100% sure. I suppose whoever is in charge of a specific coordinated project should have a role in determining some of these values, potentially with input from the partner org. In this case, I guess that's either @jdhoffa or @georgeharris2deg?

**Comment by jacobvjk** [comment]
also @georgeharris2deg @Clare2D can you confirm if the project code will be `PA2020DFS` or `PA2021DFS` after all?
I thought it was the former, but ongoing presentation seems to indicate the latter..

**Comment by Clare2D** [comment]
Good point - I believe it's PA2021DFS

**Comment by jacobvjk** [comment]
what determines this @Clare2D ? is it just a decision by anyone of us? Is it already in use anywhere? or is this already the confirmation? :)

**Comment by Clare2D** [comment]
It's what I discussed with Wim, given that it is 2021 now! But there is no hard rules on this.

**Comment by jacobvjk** [comment]
okay, sounds like a good idea to follow then

**Comment by jacobvjk** [comment]
DFS members will get the general template. closing this
