### ISSUE TITLE
transition to using a rocker image as the base

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#454]
This has been discussed a few times elsewhere, but this is meant to converge the discussion into one place and maybe/hopefully get the ball rolling on this eventually.

Right now, we use [2dii/r-packages](https://hub.docker.com/repository/docker/2dii/r-packages) (which is maintained at [2DegreesInvesting/docker/r-packages](https://github.com/2DegreesInvesting/docker/tree/master/r-packages)) as the base image for the Docker image that is used for transtionmonitor.com. It may be advantageous to instead use a popular, well-maintained Docker image (such as [rocker/verse](https://hub.docker.com/r/rocker/verse)) that includes R and many of the necessary packages already as the base image to which we add just the most use case specific changes needed.

There are a few very specific changes made in 2dii/r-packages, and we will need to ascertain if they are necessary for the final images we make for the web server...
https://github.com/2DegreesInvesting/docker/blob/9efe76454b91a45f47e32da5d5d7d440d6a8a644/r-packages/Dockerfile#L50-L53

We will also have to consider the list of installed packages and make sure that we add any that are not already installed in rocker/verse...
https://github.com/2DegreesInvesting/docker/blob/9efe76454b91a45f47e32da5d5d7d440d6a8a644/r-packages/Dockerfile#L9-L49

I do not take this change lightly... obviously we will need to do this very cautiously, and with a lot of testing.

**Comment by cjyetman** [comment]
an attempt at this, and some discussion of why this is difficult and potentially not desirable is here #481

**Comment by cjyetman** [comment]
@AlexAxthelm I bumping this since now that you have some experience building the Docker images, you may have some stronger opinions or ideas about this?

**Comment by cjyetman** [comment]
Unfortunately, I did not document precisely what was wrong with the rocker:verse based transitionmonitor Docker images that I experimented with, however, I believe that the problem may have been [this issue](https://github.com/2DegreesInvesting/create_interactive_report/issues/422) in create_interactive_report which I was not fully aware of at the time. Now that that issue was resolved by [this PR](https://github.com/2DegreesInvesting/create_interactive_report/pull/445), and given that my recent experimentation using rocker/verse:4.1.2 and R packages available as of 2021.11.18 (using RSPM) seem to work as expected (disregarding more recent problems with 2020Q4 data and memory), maybe it's time to revisit making this change?

```Dockerfile
# using R 4.1.2 and CRAN packages available as of 2021.11.18
# https://hub.docker.com/layers/rocker/verse/4.1.2/images/sha256-1e639ca754d1963cfb259c23341fef17858b8de2766f46a16095e8807cda83f9?context=explore
# https://packagemanager.rstudio.com/client/#/repos/1/overview

FROM rocker/verse:4.1.2

ARG CRAN
ENV CRAN=${CRAN:-https://packagemanager.rstudio.com/all/__linux__/focal/2021-11-17+Y3JhbiwyOjQ1MjYyMTU7MzM5RjM4RjI}
RUN echo "options(repos = c(CRAN='$CRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site

RUN tlmgr install \
    caption mathspec sectsty sourcesanspro wrapfig fancyhdr xcolor blindtext \
    titlesec lipsum amsmath iftex euenc fontspec tipa unicode-math xunicode \
    kvoptions ltxcmds kvsetkeys etoolbox auxhook bigintcalc bitset etexcmds \
    gettitlestring hycolor hyperref intcalc kvdefinekeys letltxmacro pdfescape \
    refcount rerunfilecheck stringenc uniquecounter zapfding pdftexcmds \
    infwarerr texlive-scripts geometry

RUN install2.r --skipinstalled --error \
    assertthat bookdown config conflicted countrycode crayon \
    data.table devtools dplyr DT forcats fs fst ggplot2 glue \
    highcharter here janitor jsonlite knitr plyr purrr readr readxl \
    renv reshape2 rlang rmarkdown rstudioapi scales snakecase stringr \
    testthat tibble tidyr tidyselect tidyverse usethis withr writexl yaml zoo
RUN Rscript -e 'devtools::install_github("2DegreesInvesting/r2dii.utils")'

COPY PACTA_analysis /bound
COPY create_interactive_report /create_interactive_report
COPY pacta-data /pacta-data
COPY r2dii.climate.stress.test /r2dii.climate.stress.test
COPY r2dii.stress.test.data /r2dii.stress.test.data

RUN chmod -R a+rwX /bound
RUN chmod -R a+rwX /create_interactive_report
RUN chmod -R a+rwX /pacta-data
RUN chmod -R a+rwX /r2dii.climate.stress.test
RUN chmod -R a+rwX /r2dii.stress.test.data

RUN exit 0
```

**Comment by maurolepore** [comment]
It seems worth trying :-)

Two questions:

1. I see `RUN tlmgr install` and a super quick google search suggests this installs TeX stuff. Is that not included in the rocker/verse image?

> Adds tex & publishing-related packages -- https://www.rocker-project.org/images/

2. The repo URL is passed indirectly via an environment variable. That seems a bit complicated. is that to more clearly separate (a) the thing that are likely to change more often (the date) from (b) the things that don't change (all other code)?

**Comment by cjyetman** [comment]
> 1. I see `RUN tlmgr install` and a super quick google search suggests this installs TeX stuff. Is that not included in the rocker/verse image?

Those are TeX packages that are required by [`create_executive_summary()`](https://github.com/2DegreesInvesting/create_interactive_report/blob/master/create_executive_summary.R). They're similar to R packages in that a "base" version of LaTeX does not include every package, but a repository ([CTAN](https://ctan.org/?lang=en)) allows one to easily install them. CRAN was actually modeled after CTAN and CPAN. So, no, rocker/verse does not include those specific TeX packages that are required.

> 2. The repo URL is passed indirectly via an environment variable. That seems a bit complicated. is that to more clearly separate (a) the thing that are likely to change more often (the date) from (b) the things that don't change (all other code)? (Just curious -- I like it).

exactly

**Comment by cjyetman** [comment]
also, if you're curious, this TeX packages install is the same thing we're doing in the [2dii/r-packages Dockerfile](https://github.com/2DegreesInvesting/docker/blob/9c6566df441c7aa92bdec74d20a32ef345f3b3c3/r-packages/Dockerfile#L52)...
```Dockerfile
    && Rscript -e 'tinytex::tlmgr_install(pkgs = c("caption", "mathspec", "sectsty", "sourcesanspro", "wrapfig", "fancyhdr", "xcolor", "blindtext", "titlesec", "lipsum"))' \
```
except `{tinytex}` ships with a different set of packages than rocker/verse, so there are additional TeX packages that need to be installed here.
