### ISSUE TITLE
don't use all_of() in filter()

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#484]
https://github.com/2DegreesInvesting/PACTA_analysis/blob/897433f71c18edb6ba2cf6798f4c961158f27b0d/0_web_functions.R#L51

This appears to be an "off-label" usage of [`all_of()`](url), and frankly, I find it very difficult to predict its behavior, even though apparently it seems to work the same as the more standard use of `filter()`, even when abused...
``` r
library(dplyr)
getNamespaceVersion("dplyr")
#> version 
#> "1.0.7"
getNamespaceVersion("tidyselect")
#> version 
#> "1.1.1"

df <- tibble(x = LETTERS[1:5])
df
#> # A tibble: 5 × 1
#>   x    
#>   <chr>
#> 1 A    
#> 2 B    
#> 3 C    
#> 4 D    
#> 5 E

my_filter <- "A"
df %>% filter(x == my_filter)
#> # A tibble: 1 × 1
#>   x    
#>   <chr>
#> 1 A
df %>% filter(x == all_of(my_filter))
#> # A tibble: 1 × 1
#>   x    
#>   <chr>
#> 1 A

my_filter <- c("A", "B")
df %>% filter(x == my_filter)
#> Warning in x == my_filter: longer object length is not a multiple of shorter
#> object length
#> # A tibble: 2 × 1
#>   x    
#>   <chr>
#> 1 A    
#> 2 B
df %>% filter(x == all_of(my_filter))
#> Warning in x == all_of(my_filter): longer object length is not a multiple of
#> shorter object length
#> # A tibble: 2 × 1
#>   x    
#>   <chr>
#> 1 A    
#> 2 B

my_filter <- NULL
df %>% filter(x == my_filter)
#> Error: Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `x == my_filter`.
#> x Input `..1` must be of size 5 or 1, not size 0.
df %>% filter(x == all_of(my_filter))
#> Error: Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `x == all_of(my_filter)`.
#> x Input `..1` must be of size 5 or 1, not size 0.

my_filter <- c("A", "B")
df %>% filter(x %in% my_filter)
#> # A tibble: 2 × 1
#>   x    
#>   <chr>
#> 1 A    
#> 2 B
df %>% filter(x == all_of(my_filter))
#> Warning in x == all_of(my_filter): longer object length is not a multiple of
#> shorter object length
#> # A tibble: 2 × 1
#>   x    
#>   <chr>
#> 1 A    
#> 2 B
```

I suggest changing this to `df <- df %>% filter(portfolio_name == portfolio_name_)`, as is done in other locations, such as...
https://github.com/2DegreesInvesting/PACTA_analysis/blob/897433f71c18edb6ba2cf6798f4c961158f27b0d/web_tool_script_1.R#L183-L184

Do you see any problem with that @AlexAxthelm @jacobvjk @maurolepore @jdhoffa?

**Comment by jacobvjk** [comment]
no issues from my side

**Comment by maurolepore** [comment]
I agree the use of `all_of()` here seems off-label and is best to remove it. 

``` r
library(dplyr,warn.conflicts = FALSE)

# Documented usage: You get an informative error
# > If any of the variables in the character vector is missing, an error is thrown.
not_a_member <- "C"
tibble(A = c("A", "B")) %>% select(all_of(not_a_member))
#> Error: Can't subset columns that don't exist.
#> x Column `C` doesn't exist.


# Off label and useless: You don't get an error at all
tibble(A = c("A", "B")) %>% filter(A == all_of(not_a_member))
#> # A tibble: 0 × 1
#> # … with 1 variable: A <chr>
```

I suspect the intent was to throw an error if some element of the filtering vector is not a member of the column. Do we want to implement that idea? For example:

``` r
abort_if_not_a_member <- function(x, y) {
  if (!all(y %in% x)) {
    stop(
      "Each element of `y` must be a member of `x`.\n",
      "Not a member: ", toString(setdiff(y, x)),
      call. = FALSE
    )
  }
  
  invisible(data)
}

data <- data.frame(x = c("a", "b"))
y <- c("b", "c", "d")

setdiff(y, data$x)
#> [1] "c" "d"
abort_if_not_a_member(data$x, y)
#> Error: Each element of `y` must be a member of `x`.
#> Not a member: c, d
```

**Comment by jdhoffa** [comment]
No issue from my side, get it out of there!!!!

**Comment by cjyetman** [comment]
> I suspect the intent was to throw an error if some element of the filtering vector is not a member of the column. Do we want to implement that idea? For example:


Thanks, but... I'd rather not guess what the intent was, because honestly it's not clear to me.

**Comment by cjyetman** [comment]
> As for the proposed fix (`df <- df %>% filter(portfolio_name == portfolio_name_)`, I can accept it, under minor protest. I don't like it when variables share names with columns, since it increases mental load while debugging to differentiate between the two. But I acknowledge that it's consistent with existing code, and a minor quibble.

agreed... in the matching PR #486, I used `df <- df %>% filter(portfolio_name == .env$portfolio_name)` to be more explicit

**Comment by AlexAxthelm** [comment]
I'm similarly uneasy with the need to call `.env` ever, since that suggests to me that there's some strong problems in the design patterns, and we aren't scoping objects correctly.  but I think that what you have in #486 is better than what we had, andd probably as good as we can get without some pretty major refactoring.

**Comment by maurolepore** [comment]
RE `.env$` let me politely disagree with you @AlexAxthelm.  I like `.env$` even if the name doesn't clash with an existing name right now. It protects against the unintentional introduction of a clash in the future, and flags something weird is going on (in the context of dplyr, "weird" is that the symbol refers not to a column in the data mask but to a variable in the scope of the function (hopefully not outside).

**Comment by AlexAxthelm** [comment]
I see your point @maurolepore. I think my unease with all of this stems back to the fact that this is the issue that I disagree most strongly with Hadley&Co about. Similarly, I don't think that `dplyr::filter()` (or other functions that lean heavily on NSE) should make it into production code, and instead I prefer using `filter_at` and friends.

```r
foo <- 6

#bad
filter(mtcars, cyl == foo)

#good
dplyr::filter_at(mtcars, vars("cyl"), all_vars(. == foo))
```

**Comment by cjyetman** [comment]
> in the context of dplyr, "weird" is that the symbol refers not to a column in the data mask but to a variable in the scope of the function.

💯

**Comment by cjyetman** [comment]
> Similarly, I don't think that `dplyr::filter()` (or other functions that lean heavily on NSE) should make it into production code, and instead I prefer using `filter_at` and friends.

`filter_at()` and friends are [superseded](https://dplyr.tidyverse.org/articles/colwise.html#if-_at-_all) in favor of `across()`

**Comment by cjyetman** [comment]
closed by 1bfb1de63a5734f9101af0fa0f0f3c300d9d5f04

**Comment by AlexAxthelm** [comment]
> `filter_at()` and friends are [superseded](https://dplyr.tidyverse.org/articles/colwise.html#if-_at-_all) in favor of `across()`

Thanks for pointing me towards this. apparently it's been a while since I pushed tidyverse-based code to production

**Comment by cjyetman** [comment]
> Thanks for pointing me towards this. apparently it's been a while since I pushed tidyverse-based code to production

it's hard to keep up with `tidyverse` considering how quickly it evolves 😬
