### ISSUE TITLE
change `portfolio_name_in` to `portfolio_name` in portfolio parameter files

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#485]
In the existing example portfolio parameter files, `portfolio_name_in` and `investor_name_in` keys are used. However, the code that reads in the portfolio parameter file looks for keys `portfolio_name` and `investor_name`, which works anyway by accident, as far as I can tell, because Extract (`$`) does partial matching.

https://github.com/2DegreesInvesting/PACTA_analysis/blob/897433f71c18edb6ba2cf6798f4c961158f27b0d/0_web_functions.R#L94-L95

I propose to universally change the keys `portfolio_name_in` and `investor_name_in` to `portfolio_name` and `investor_name` everywhere in this repo, which at the moment only appears in the existing example portfolio parameter files, and here...
https://github.com/2DegreesInvesting/PACTA_analysis/blob/897433f71c18edb6ba2cf6798f4c961158f27b0d/workflow-pacta-cop.Rmd#L490-L491

@AlexAxthelm do you agree?

**Comment by AlexAxthelm** [comment]
Why are we bothering with these variables in the first place? I know it looks a little clumsier in the code, but I think my preference to call upon `cfg` as a consistent object. that might look like:

```r
foo(
  portfolio = cfg$parameters$portfolio_name,
  investor = cfg$parameters$investor_name
)
```

**Comment by AlexAxthelm** [comment]
But if we have a strong preference for keeping the variables, I'd rather have `*_in` (or some other suffix) to distinguish a parameter from a column name or a variable valued object.

**Comment by cjyetman** [comment]
> Why are we bothering with these variables in the first place? I know it looks a little clumsier in the code, but I think my preference to call upon `cfg` as a consistent object. that might look like:
> 
> ```r
> foo(
>   portfolio = cfg$parameters$portfolio_name,
>   investor = cfg$parameters$investor_name
> )
> ```

not sure I understand?

**Comment by cjyetman** [comment]
> But if we have a strong preference for keeping the variables, I'd rather have `*_in` (or some other suffix) to distinguish a parameter from a column name or a variable valued object.

this would be a massive change, because in the R code (not the YAML files), it's always referred to as `portfolio_name`... I would guess that would be a high risk change

**Comment by cjyetman** [comment]
I definitely don't "prefer" this over anything else, conceptually...
```r
# config reading code
cfg <- config::get()
portfolio_name_in <<- cfg$parameters$portfolio_name 
investor_name_in <<- cfg$parameters$investor_name 
```
but I'm certainly not suggesting that we change that here. I'm not opposed to idea of changing that in some long-run hypothetical future, but that would be a major disruption and likely require changes to hundreds of lines of code.

All I'm suggesting here is to get rid of this `portfolio_name_in` in the example configuration files because there doesn't seem to be any reason for it to exist, and frankly I'm pretty sure it only works by accident. Additionally, it causes confusion because you set `portfolio_name_in` in the config file, and then if you try to see in the code where/how that impacts things, it's very difficult because that object name doesn't;t exist anywhere in the code. I think it's much more natural that if you set in a config file `portfolio_name_in: MyPortfolio` that you would expect that gets imported into the environment somewhere as `portfolio_name_in` (whether it's directly in the environment or as an element in a list `cfg` or `options` or whatever, e.g. `options$portfolio_name_in`)... to me it's nonsensical that you set in the config file `portfolio_name_in: MyPortfolio` and then in the environment you get `portfolio_name` or `cfg$portfolio_name`.

**Comment by AlexAxthelm** [comment]
> Additionally, it causes confusion because you set `portfolio_name_in` in the config file, and then if you try to see in the code where/how that impacts things, it's very difficult because that object name doesn't;t exist anywhere in the code

Agreed.
