### ISSUE TITLE
Move Project name and file paths to yml file and ignore this file

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#49]
While we're here, I propose we extract the "project_name" to a config file. 
This way we won't have merge conflicts every time somebody is working on a different project

_Originally posted by @jdhoffa in https://github.com/2DegreesInvesting/PACTA_analysis/pull/48#discussion_r459296636_

**Comment by Clare2D** [comment]
Jacob are you able to do this? Both the project_name and the true/false on external/internal and the file paths. 
Thanks!

**Comment by jacobvjk** [comment]
I think I can figure that out, will add it to the agenda

**Comment by jdhoffa** [comment]
Closed by #51
