### ISSUE TITLE
Better handling of data from dropbox

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/PACTA_analysis#50]
@Clare2D This is a quick gain we can make, while the ongoing discussions over why we are using dropbox and who will take over transferring to a better system continue:

In this repo, we should pull all dropbox data directly from the server (rather than these local paths etc.) 

To do so, I would use the package `rdrop2`. Using this package, each 2dii internal can generate an `.httr-oauth` (this ABSOLUTELY MUSTN'T BE COMMITTED TO VERSION CONTROL) luckily, the function `rdrop2::drop_auth()` allows  a user to automatically authenticate their dropbox account, and adds the file to .gitignore. 

This is probably the biggest return/effort value we can get in cleaning up this repo.
See snippet below for an example of how easy it is to use/ access files using `rdrop2` (also note that the "test_data" is under the  "2º Investing Initiative" directory with the pesky degree symbol, but in general most of our data lives under PortCheck, meaning we can bypass a lot of the text encoding headaches that plague us).

``` r
library(dplyr)
library(rdrop2)

# this command automatically pulls up a browser window to authenticate
# your dropbox account
rdrop2::drop_auth()

# note the sensitive .httr-oauth file is automatically added to
# .gitignore
rdrop2::drop_dir() %>% select(name, path_lower)
## # A tibble: 4 x 2
##   name              path_lower        
##   <chr>             <chr>             
## 1 2° Investing Team /2° investing team
## 2 PortCheck         /portcheck        
## 3 PortCheck_v2      /portcheck_v2     
## 4 Camera Uploads    /camera uploads   


rdrop2::drop_dir("/2° investing team/people/jackson/rdrop_test") %>% 
    select(name, path_lower)
## # A tibble: 2 x 2
##   name     path_lower                                           
##   <chr>    <chr>                                                
## 1 test.csv /2° investing team/people/jackson/rdrop_test/test.csv
## 2 test.rda /2° investing team/people/jackson/rdrop_test/test.rda


# reading csvs comes right out of the box
test1 <- rdrop2::drop_read_csv("/2° investing team/people/jackson/rdrop_test/test.csv")
Downloaded /2° investing team/people/jackson/rdrop_test/test.csv to /var/folders/qd/7pm957711f53yclkzv_1tgmh0000gn/T//RtmpjXdNMy/test.csv: 38 bytes on disk
  |===========================================================| 100%

test1
##   name date
## 1  foo 2020
## 2  bar 2021
## 3 fizz 2022


# reading rdas takes a bit more code, but we can easily just write a
# wrapper around this
drop_read_rds <- function(file, dest = tempdir(), dtoken = rdrop2:::get_dropbox_token(), 
    ...) {
    
    localfile = paste0(dest, "/", basename(file))
    drop_download(file, localfile, overwrite = TRUE, dtoken = dtoken)
    readr::read_rds(localfile, ...)
}

test2 <- drop_read_rds("/2° investing team/people/jackson/rdrop_test/test.rda")
Downloaded /2° investing team/people/jackson/rdrop_test/test.rda to /var/folders/qd/7pm957711f53yclkzv_1tgmh0000gn/T//RtmpjXdNMy/test.rda: 263 bytes on disk
  |===========================================================| 100%

test2
## # A tibble: 3 x 2
##   name   date
##   <chr> <int>
## 1 foo    2020
## 2 bar    2021
## 3 fizz   2022
```

@pranavpandya84 I seem to recall you brought this up a LONG time ago, and it was never really taken up, so a big thank you to you for that. 
@jacobvjk this could be a medium-sized task you could take on, time permitting, to help deal with some of our technical debt (I'd be happy to oversee you through the process)

**Comment by jacobvjk** [comment]
sure, happy to do this, once prioritised @jdhoffa

**Comment by jdhoffa** [comment]
Relates to #44

**Comment by jdhoffa** [comment]
I'll leave it to @Clare2D to prioritize, just let me know when/ if you take it on.

**Comment by cjyetman** [comment]
I think this is not a great idea... since I would guess ideally we would not force using Dropbox, but rather make the use of Dropbox possible and easy with no negative consequences. I think we should read and write (or otherwise access) files with standard commands that work for any file system...

if the file system is a local copy of Dropbox, then determine the appropriate local file path and give that to the standard i/o commands...

if the file system is non-local hosted version of Dropbox (or other online repository), maybe use `rdrop2` or other process to generate a file connection and give that to the standard i/o commands

**Comment by cjyetman** [comment]
is this relevant anymore? @Clare2D @jdhoffa @jacobvjk

**Comment by Clare2D** [comment]
Good question. Sorry it seems I dropped the ball on answering this one.

**Comment by Clare2D** [comment]
I don't think this is necessarily the right solution any more. I will close this and we can discuss how we source data in the new year.
