### ISSUE TITLE
Re-introduce bics_sector at some point

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#65]
https://github.com/2DegreesInvesting/PACTA_analysis/blob/d99f325da586728104c985e12ccfecb1af1fc155/0_portfolio_input_check_functions.R#L1211

currently not working, but in principle bics_sector should be here instead of (or additionally to?) security_mapped_sector

fyi
@Clare2D

**Comment by jacobvjk** [comment]
https://github.com/2DegreesInvesting/PACTA_analysis/pull/78

**Comment by Clare2D** [comment]
Solved this. Needs to be bought through my commits on the current_web_func branch
