### ISSUE TITLE
Equity Market List either "Global" or "GlobalMarket" still causing trouble sometimes

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#83]
Financial supervisors in Norway still had an equity market list filtering issue, where setting it to GlobalMarket removed all equity data.

We should decide if we doe a complete overhaul that forces One of the two in every case or if we just always allow the `equity_market_list %in% c("Global", "GlobalMarket")`.

While the latter is not very elegant and consistent, it would lead to less potential issues of such a transition.

Any preferences @Clare2D ?

**Comment by Clare2D** [comment]
Not sure I've understood the alternatives here. Let's discuss when you're back!

**Comment by Clare2D** [comment]
Do we still need to discuss?

**Comment by jacobvjk** [comment]
quick discussion would not hurt
