### ISSUE TITLE
Can we use a single main line of development?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#92]
I moved this discussion from #90 to here.

> We should discuss the webtool scripts and branch. It seems that merging the branch this is the better thing to do.

-- @Clare2D 

> regarding the branch/repo discussion: would be great to talk about this this week, as we should also consider how the stress testing modules will fit into the future repo structure and this should ideally already be considered when I make the changes in that for P2020

-- @jacobvjk

**Comment by maurolepore** [comment]
@jacobvjk, @Clare2D, @cjyetman, @MonikaFu,

This issue was one of the topics we discussed yesterday. You may remember I changed the default branch from `master` to `current_web_functionality`. The advantage I shared during the meeting is that the new base branch plays well with tools to submit pull requests (e.g. [experiment 1 with `gh`](https://github.com/2DegreesInvesting/PACTA_analysis/pull/111), [experiment 2 with usethis](https://github.com/2DegreesInvesting/PACTA_analysis/pull/112)).

However, I now realize this approach doesn't meet Clare's goal of exposing the `master` branch on the home page of the repo -- instead the branch exposed is now `current_web_functionality`; i.e. the home page shows this (notice the branch button):

<img src=https://user-images.githubusercontent.com/5856545/94992461-ccb68100-054f-11eb-8bf2-7198d2eb2fdb.png width=300>





## My suggestion

I think the feature Clare wants is more commonly managed via releases. 

Instead of exposing the latest release and hiding the in-development version, open source projects commonly expose the in-development version and provide easy access to released versions, particularly the latest release.

### An example

For example, take the `gh` program to interact with GitHub from the command line. 

* GitHub repo exposes the in-development version in the base branch `trunk` (they don't use a branch `master`, likely because GitHub aims to abandon the term "master" because of its connection with slavery): https://github.com/cli/cli

<img src=https://user-images.githubusercontent.com/5856545/94992580-9b8a8080-0550-11eb-8a94-5b4be850a9e7.png width=300>

The latest release is prominently advertised on the home page, and links to other releases are also there -- just a bit less obvious:

<img src=http://i.imgur.com/LyCF7Xr.png width=200>

### What this means for us

I suggest we follow the common practice.

* The home page of the repo exposes the in-development branch, now `current_web_functionality`:

<img src=http://i.imgur.com/T9VM5k2.png width=300>


* What is right now on `master` (commit d7c1a8fda4d653d1e7d843c99b0a82c27f61f682) is now the latest release and is prominently linked from the home page:

<img src=http://i.imgur.com/3or0Fuq.png width=600>

* Users can click on "latest" and land in the release page, then download the source code and use it as they would normally do. 

<img src=http://i.imgur.com/Rd7X1C3.png width=300>

* Notice that the latest release -- version `0.0.0` -- points to the same commit where `master` points today.

<img src=http://i.imgur.com/xeraLQL.png width=100>

<img src=http://i.imgur.com/li9cU7p.png width=600>

### What next?

If we manage the project as I explain here, then we don't need to keep two long-lived branches. What's now on `master` is now safely stored in release `0.0.0`, and what's now on `current_web_tool` could be moved to `master`, maybe via `git merge -X<appropriate strategy>` or via `git checkout master && git reset --hard current_web_functionality` (WARNING: this last approach rewrites history so everyone would need to hard reset their local repos too).

--

Feel free to drop your questions here or schedule a meeting to discuss this topics specifically.

**Comment by Clare2D** [comment]
Hey Mauro. thanks for identifying and resolving this. Having spoken to @jacobvjk about this again, we think it's best to merge the current web functionality into the master branch and not have to deal with this at all. I don't think this is going to be too much of a challenge but think this is critical for us to proceed on development. I will set up a PR and see what the conflicts look like and perhaps we can discuss best workflow on the merge.
