### ISSUE TITLE
Can BoE ST code be removed from PACTA_analysis repo

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/PACTA_analysis#94]
It seems to me like it can. Unless @Clare2D has any objections, I would consider the BoE code and stress testing code that are currently in this repo dead code and remove it.

Original message:

If it's unclear, I suggest you open another issue to remember, and come back to it once we have more tests -- i.e. a safety net to know if removing this code would actually break anything useful.

_Originally posted by @maurolepore in https://github.com/2DegreesInvesting/PACTA_analysis/pull/87#issuecomment-700647901_

Also:
@maurolepore @Clare2D these functions have little to do with what we currently run as the stress test. This must be a pretty old version, probably used in the BoE study and I would suggest I do not try to dive into this as we should use the new version from this Stress Testing repo anyway https://github.com/2DegreesInvesting/StressTestingModelDev

**Comment by Clare2D** [comment]
This can be removed. The only used part of this is in the webtool repo so no need to worry

**Comment by jacobvjk** [comment]
@Clare2D we are talking about which webtool repo here?

**Comment by Clare2D** [comment]
The original, not what you're working on!
